version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: payflow-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: payflow-test
    depends_on:
      - app
    volumes:
      - .:/app
